### ISSUE TITLE
Add a "snap to tail" UI

### ISSUE THREAD

**Issue by lwouis** [joffrey-bion/fx-log#3]
Add some UI element to snap the file's tail

**Comment by joffrey-bion** [comment]
It looks like I can't scroll programatically. The `scrollpane.SetVvalue()` method has no effect, which is weird.
This bug should have been resolved as I'm using JDK8_u65:
https://bugs.openjdk.java.net/browse/JDK-8093745
https://bugs.openjdk.java.net/browse/JDK-8096249

**Comment by lwouis** [comment]
I think the keyboard shortcut to jump to the tail could be spacebar.

**Comment by joffrey-bion** [comment]
Done in commit fc672f7dd21b5adce482872efc49c1e66626116e

And the keyboard shortcut _is_ the sapcebar (when the table is focused) :smile: 
However, I couldn't manage to unlock the "follow tail" programmatically. Scrolling to the second last row doesn't do the trick. It will probably be solved at the same time as the slow scroll drifting (issue https://github.com/joffrey-bion/fx-log/issues/18).
