### ISSUE TITLE
Search/highlight without filtering

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/fx-log#35]
The filtering feature is nice, but it would also be nice to be able to keep context when searching for something. Right now, if I use a regex at the top, then I only see the matching lines, but I can't see their context.

A basic search feature should also be available to just _highlight_ some words, go from one occurrence to the other, etc. Without removing all other "irrelevant" lines, that may bring context and in fact be useful.

Related:
https://github.com/joffrey-bion/fx-log/issues/34

**Comment by lwouis** [comment]
This for me is the selling feature. I think if you implement this the app will see much more usage (at least at work :p)

**Comment by joffrey-bion** [comment]
It is already possible to add a temporary columnization rule that fulfils this purpose. The point of this issue is just to make it more convenient to use (with a plain text field instead of persistent rules), and to add granularity to the highlight.
