### ISSUE TITLE
Filter field should be case-insentive by default

### ISSUE THREAD

**Issue by lwouis** [joffrey-bion/fx-log#37]
The search field is currently matching case-sentitive regexes. I think a better design (to fit most common use-cases) would be to have that box only check for case-insensitive substrings, then have a checkbox besides the search field to switch to regex input.

That way the default behaviour covers 80% cases, and then checking the box helps you answer the remaining 20% cases.

**Comment by joffrey-bion** [comment]
This is interesting, I'll need to find a nice design taking into account the plain search (simply highlighting without filtering) raised in issue https://github.com/joffrey-bion/fx-log/issues/35
