### ISSUE TITLE
Add the version number in the Help menu

### ISSUE THREAD

**Issue by lwouis** [joffrey-bion/fx-log#42]
It would be helpful to have a new "About" submenu in "Help". It would display the version number (+ commit number maybe also would be cool) of the running application. It could also display the author, website, etc.

Just the typical about popup

**Comment by joffrey-bion** [comment]
I recently worked on the changelog generation. Next step is to include the help>about menu ;-)
It will contain:
- version
- version build date
- changelog or link to it
- author
- link to bintray repo

I didn't think about the commit number, I'm not sure it's useful, though.
