### ISSUE TITLE
Column windows selector doesn't close properly

### ISSUE THREAD

**Issue by IvanoAlvino** [joffrey-bion/fx-log#53]
A small bug I noticed is that when you click on th small '+' sign top right to select/deselect the tabs you want to show it correctly opens the window, but than when you click again on the '+' sign you expect the small window to close.
What actually happens is that the small window doesn't close and instead it switch position (by a small amount of pixels).
You have to actually click anywhere else to close the windows.

**Comment by joffrey-bion** [comment]
This is a built-in feature of JavaFX, so I don't have any control over it. I might be able to override the default behaviour in some way, but I'm not sure it is worth spending time on it.

**Comment by IvanoAlvino** [comment]
Ok, good to know.
Anyway is not important fix, I wouldn't spend time on that given the situation you explained.
