### ISSUE TITLE
Limit number of logs displayed

### ISSUE THREAD

**Issue by titusdream** [joffrey-bion/fx-log#61]
if the server.log file becomes larger, fx-log will take considerable amount of memory (4.8G+ memory when log file around 750M), this often makes the intellj debugger hangs the flow due to short of memory.
Not sure if it's possible to tail read file in java ? or keep only limited info in memory and drop the old lines ?

**Comment by joffrey-bion** [comment]
I had planned to implement that at first, but then I counted on log rotation to prevent memory problems.
It looks like a setting for a max number of lines could be useful anyway for low memory computers, or just for people who want fast filtering when mostly dealing with the last logs.

Current workaround: use the "clear" button more often! :)
