### ISSUE TITLE
Refine CSS for dark theme

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/fx-log#7]
Several UI issues boil down to one source problem: the CSS of the dark theme hasn't been thought through.

Examples:
- text is too white
- menus are hard to distinguish from their background

**Comment by joffrey-bion** [comment]
We might find some interesting stuff here:
- metro dark theme: http://code.makery.ch/library/javafx-8-tutorial/part4/
- original modena.css: https://gist.github.com/maxd/63691840fc372f22f470

**Comment by lwouis** [comment]
Listing some specific improvements:
- Remove all the cell lines. Delimitation doesn't need to be enforced with lines (I have a cool book on that if you are interested). Plus there are already zebra backgrounds.
- The blue background when a line is selected is too intense on a dark theme.

**Comment by joffrey-bion** [comment]
Agreed. For your first point, the alternating row background has actually been added recently. Until now, the rows' background was overridden by the default dark colorizer, which hid these separating lines.
