### ISSUE TITLE
Display progress when loading very large file

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/fx-log#93]
We can't know exactly how many lines there is in the file, so we have to estimate. To start with, maybe we can ask the system for the size of the file, and approximate how big is each line to display some sort of progress relative to the global size. When the end of file is reached, we can mark 100%.

Anyway, we should find a solution to #95 first, of course.

**Comment by joffrey-bion** [comment]
We can't know exactly how many lines there is in the file, so we have to estimate. To start with, maybe we can ask the system for the size of the file, and approximate how big is each line do display some sort of progress. When the end of file is reached, we can mark 100%.

**Comment by lwouis** [comment]
How can you approximate the size of a line? Size can vary hugely. You may find an empirical average for one type of log, but even then, it sucks to mislead the user in those cases where huge lines appear... which is when they are likely to look at this information anyway.

You need to estimate progress with [bytes read] / [bytes to read].

**Comment by joffrey-bion** [comment]
Yes, I was talking about approximating the size of each line _once read_, to have an estimate of the number of bytes read, not a general approximation of how big logs are in general. The number of characters in the line is a good approximation of its size in bytes to start with. Otherwise I can also modify the Apache tailer to get the exact number of bytes read, but that's unnecessary IMO, the user just wants to have a sense of progress.

**Comment by joffrey-bion** [comment]
Issue #95 being fixed, there is no pressing need for this kind of progress bar.
Also, when we're tailing, progress doesn't really make sense.
What would make more sense is to display how many bytes behind the actual file we currently are, but this requires hacking into the Apache `Tailer` and I'm not sure it is worth the effort. It does not seem like a very useful piece of information to the user.
